// This page serves as the main results dashboard, summarizing the user's profile and providing personalized recommendations.
import React, { useEffect, useState } from "react";
import { useNavigate } from "react-router-dom";
import { CheckCircle, AlertCircle, User, Activity, Brain, Cigarette, Wine, Heart } from "lucide-react";
import { getUserProfile, getPersonalizedRecommendations, getUserRiskFactors, getAgeGroupDisplay } from "../utils/userProfile";

const ResultsPage = () => {
  const navigate = useNavigate();
  // These state variables hold the data generated by the userProfile utility functions.
  const [userProfile, setUserProfile] = useState(null);
  const [recommendations, setRecommendations] = useState(null);
  const [riskFactors, setRiskFactors] = useState([]);

  useEffect(() => {
    // This hook loads the user's profile and then immediately generates the recommendations and risk factors based on that profile.
    const profile = getUserProfile();
    const recs = getPersonalizedRecommendations();
    const risks = getUserRiskFactors();
    
    setUserProfile(profile);
    setRecommendations(recs);
    setRiskFactors(risks);

    // It also marks the results page as visited.
    const visited = JSON.parse(localStorage.getItem("pirha_visited_sections") || '{"sections":[]}');
    if (!visited.sections.includes("results")) {
      visited.sections.push("results");
      localStorage.setItem("pirha_visited_sections", JSON.stringify(visited));
    }
  }, []);

  if (!userProfile || !recommendations) {
    return <div className="min-h-screen bg-gray-50 p-4">Ladataan tuloksia...</div>;
  }

  // This function calculates an overall risk level ('high', 'medium', or 'low') based on the number and severity of the user's identified risk factors.
  const getRiskLevel = () => {
    const highRisks = riskFactors.filter(r => r.level === 'high').length;
    const mediumRisks = riskFactors.filter(r => r.level === 'medium').length;
    
    if (highRisks >= 2) return { level: 'high', color: 'red', text: 'Korkea' };
    if (highRisks >= 1 || mediumRisks >= 2) return { level: 'medium', color: 'yellow', text: 'Kohtalainen' };
    return { level: 'low', color: 'green', text: 'Matala' };
  };

  const riskLevel = getRiskLevel();

  // This function's purpose is to create a sorted list of the most important content sections for the user.
  const getRelevantSections = () => {
    const sections = [];
    
    // It always includes certain sections (like Movement and Nutrition) and conditionally includes others (like Substance Use or Other Diseases) based on the user's profile.
    sections.push({
      path: "/movement",
      title: "Liikkuminen",
      icon: Activity,
      priority: userProfile.lifestyle.includes('low_activity') ? 'high' : 'normal',
      reason: userProfile.lifestyle.includes('low_activity') ? 
        'Vähäinen liikunta - erityisen tärkeä' : 'Fyysinen kunto on tärkeää toipumiselle'
    });

    sections.push({
      path: "/nutrition",
      title: "Ravitsemus",
      icon: Heart,
      priority: 'normal',
      reason: 'Hyvä ravitsemus tukee toipumista'
    });

    sections.push({
      path: "/mental-wellbeing",
      title: "Henkinen jaksaminen",
      icon: Brain,
      priority: userProfile.healthConditions.includes('mental_health') ? 'high' : 'normal',
      reason: userProfile.healthConditions.includes('mental_health') ? 
        'Mielenterveyden tuki tärkeää' : 'Henkinen valmistautuminen auttaa'
    });

    if (userProfile.lifestyle.includes('smoking') || userProfile.lifestyle.includes('alcohol')) {
      sections.push({
        path: "/substance-use",
        title: "Päihteiden käyttö",
        icon: userProfile.lifestyle.includes('smoking') ? Cigarette : Wine,
        priority: 'high',
        reason: userProfile.lifestyle.includes('smoking') ? 
          'Tupakoinnin lopettaminen kriittistä' : 'Alkoholin vähentäminen tärkeää'
      });
    }

    if (userProfile.healthConditions.length > 0) {
      sections.push({
        path: "/other-diseases",
        title: "Muut sairaudet",
        icon: Heart,
        priority: 'high',
        reason: `${userProfile.healthConditions.length} sairautta vaatii huomiota`
      });
    }

    // The sorting mechanism pushes "high" priority sections to the top of the list.
    return sections.sort((a, b) => {
      if (a.priority === 'high' && b.priority !== 'high') return -1;
      if (b.priority === 'high' && a.priority !== 'high') return 1;
      return 0;
    });
  };

  const relevantSections = getRelevantSections();

  return (
    <div className="min-h-screen bg-gray-50 p-4">
      <div className="max-w-4xl mx-auto">
        {/* Header and Profile Summary: This section gives a quick overview of the user's profile. */}
        <div className="bg-white rounded-lg shadow-md p-6 mb-6">
          <div className="flex items-center mb-4">
            <User className="w-8 h-8 text-blue-600 mr-3" />
            <div>
              <h1 className="text-2xl font-bold text-gray-900">Henkilökohtaiset suosituksesi</h1>
              <p className="text-gray-600">Perustuu antamiisi tietoihin</p>
            </div>
          </div>

          {/* User Profile Summary */}
          <div className="mt-4 p-4 bg-blue-50 rounded-lg">
            <h2 className="font-semibold text-blue-900 mb-2">Profiilisi yhteenveto:</h2>
            <div className="grid md:grid-cols-2 gap-3 text-sm">
              <div>
                <span className="font-medium">Ikäryhmä:</span> {getAgeGroupDisplay(userProfile.ageGroup)}
              </div>
              <div>
                <span className="font-medium">Riskitaso:</span>{" "}
                <span className={`font-semibold text-${riskLevel.color}-600`}>
                  {riskLevel.text}
                </span>
              </div>
              {userProfile.lifestyle.length > 0 && (
                <div className="md:col-span-2">
                  <span className="font-medium">Elämäntavat:</span>{" "}
                  {userProfile.lifestyle.map(l => {
                    const labels = {
                      'smoking': 'Tupakointi',
                      'alcohol': 'Alkoholin käyttö',
                      'low_activity': 'Vähäinen liikunta'
                    };
                    return labels[l];
                  }).join(', ')}
                </div>
              )}
              {userProfile.healthConditions.length > 0 && (
                <div className="md:col-span-2">
                  <span className="font-medium">Terveydentila:</span>{" "}
                  {userProfile.healthConditions.map(c => {
                    const labels = {
                      'diabetes': 'Diabetes',
                      'sleep_apnea': 'Uniapnea',
                      'heart_disease': 'Sydänsairaus',
                      'mental_health': 'Mielenterveyden haasteet'
                    };
                    return labels[c];
                  }).join(', ')}
                </div>
              )}
            </div>
          </div>
        </div>

        {/* This card lists out each identified risk factor and its severity level with a colored badge. */}
        {riskFactors.length > 0 && (
          <div className="bg-white rounded-lg shadow-md p-6 mb-6">
            <h2 className="text-xl font-semibold mb-4 flex items-center">
              <AlertCircle className="w-6 h-6 text-yellow-600 mr-2" />
              Riskitekijäsi
            </h2>
            <div className="space-y-2">
              {riskFactors.map((risk, index) => (
                <div key={index} className="flex items-center justify-between p-3 bg-gray-50 rounded-lg">
                  <span className="text-gray-700">{risk.factor}</span>
                  <span className={`px-3 py-1 rounded-full text-xs font-semibold ${
                    risk.level === 'high' ? 'bg-red-100 text-red-800' :
                    risk.level === 'medium' ? 'bg-yellow-100 text-yellow-800' :
                    'bg-green-100 text-green-800'
                  }`}>
                    {risk.level === 'high' ? 'Korkea' :
                     risk.level === 'medium' ? 'Kohtalainen' : 'Matala'}
                  </span>
                </div>
              ))}
            </div>
          </div>
        )}

        {/* This is the most critical section, highlighting the most important actions for the user to take. */}
        {recommendations.priority.length > 0 && (
          <div className="bg-red-50 border border-red-200 rounded-lg p-6 mb-6">
            <h2 className="text-xl font-semibold mb-4 text-red-900">
              🎯 Prioriteettisuositukset - Keskity näihin ensin
            </h2>
            <ul className="space-y-3">
              {recommendations.priority.map((rec, index) => (
                <li key={index} className="flex items-start">
                  <CheckCircle className="w-5 h-5 text-red-600 mr-2 flex-shrink-0 mt-0.5" />
                  <span className="text-red-800">{rec}</span>
                </li>
              ))}
            </ul>
          </div>
        )}

        {/* This section provides direct navigation links to the content pages determined to be most important by the getRelevantSections function, highlighting high-priority ones visually. */}
        <div className="bg-white rounded-lg shadow-md p-6 mb-6">
          <h2 className="text-xl font-semibold mb-4">Sinulle tärkeimmät sisällöt</h2>
          <div className="space-y-3">
            {relevantSections.map((section) => {
              const Icon = section.icon;
              return (
                <div
                  key={section.path}
                  onClick={() => navigate(section.path)}
                  className={`p-4 border rounded-lg cursor-pointer transition-all hover:shadow-md ${
                    section.priority === 'high' ? 'border-red-300 bg-red-50' : 'border-gray-200 hover:bg-gray-50'
                  }`}
                >
                  <div className="flex items-center justify-between">
                    <div className="flex items-center">
                      <Icon className={`w-6 h-6 mr-3 ${
                        section.priority === 'high' ? 'text-red-600' : 'text-gray-600'
                      }`} />
                      <div>
                        <h3 className="font-semibold text-gray-900">{section.title}</h3>
                        <p className="text-sm text-gray-600">{section.reason}</p>
                      </div>
                    </div>
                    {section.priority === 'high' && (
                      <span className="px-2 py-1 bg-red-100 text-red-800 text-xs font-semibold rounded">
                        Tärkeä
                      </span>
                    )}
                  </div>
                </div>
              );
            })}
          </div>
        </div>

        {/* This section provides more detailed, categorized recommendations. */}
        <div className="bg-white rounded-lg shadow-md p-6 mb-6">
          <h2 className="text-xl font-semibold mb-4">Kategoriakohtaiset suositukset</h2>
          
          {recommendations.exercise.length > 0 && (
            <div className="mb-4">
              <h3 className="font-semibold text-blue-800 mb-2">💪 Liikunta</h3>
              <ul className="space-y-1 text-sm text-gray-700">
                {recommendations.exercise.map((rec, index) => (
                  <li key={index}>• {rec}</li>
                ))}
              </ul>
            </div>
          )}

          {recommendations.nutrition.length > 0 && (
            <div className="mb-4">
              <h3 className="font-semibold text-green-800 mb-2">🍎 Ravitsemus</h3>
              <ul className="space-y-1 text-sm text-gray-700">
                {recommendations.nutrition.map((rec, index) => (
                  <li key={index}>• {rec}</li>
                ))}
              </ul>
            </div>
          )}

          {recommendations.lifestyle.length > 0 && (
            <div className="mb-4">
              <h3 className="font-semibold text-purple-800 mb-2">🌟 Elämäntavat</h3>
              <ul className="space-y-1 text-sm text-gray-700">
                {recommendations.lifestyle.map((rec, index) => (
                  <li key={index}>• {rec}</li>
                ))}
              </ul>
            </div>
          )}

          {recommendations.medical.length > 0 && (
            <div className="mb-4">
              <h3 className="font-semibold text-red-800 mb-2">⚕️ Lääketieteelliset</h3>
              <ul className="space-y-1 text-sm text-gray-700">
                {recommendations.medical.map((rec, index) => (
                  <li key={index}>• {rec}</li>
                ))}
              </ul>
            </div>
          )}
        </div>

        {/* This final section gives the user clear next steps and buttons to navigate to the most important content or to the all-content view. */}
        <div className="bg-gradient-to-r from-blue-500 to-blue-600 rounded-lg shadow-md p-6 text-white">
          <h2 className="text-xl font-semibold mb-4">Seuraavat askeleesi</h2>
          <ol className="space-y-2 mb-4">
            <li>1. Käy läpi prioriteettisuositukset</li>
            <li>2. Tutustu sinulle tärkeimpiin sisältöihin</li>
            <li>3. Lataa henkilökohtaiset PDF-oppaat</li>
            <li>4. Aloita valmistautuminen heti</li>
          </ol>
          <div className="flex gap-4">
            <button
              onClick={() => navigate(relevantSections[0]?.path || '/movement')}
              className="bg-white text-blue-600 px-6 py-3 rounded-lg hover:bg-gray-100 transition-colors"
            >
              Aloita tärkeimmästä
            </button>
            <button
              onClick={() => navigate('/all-content')}
              className="bg-blue-400 text-white px-6 py-3 rounded-lg hover:bg-blue-300 transition-colors"
            >
              Näytä kaikki sisällöt
            </button>
          </div>
        </div>
      </div>
    </div>
  );
};

export default ResultsPage;